
-- ================================================
-- SEED MEAL TEMPLATES
-- ================================================

-- Breakfast templates
INSERT INTO public.meal_templates (name, goal_type, meal_type, servings, per_serving_calories, per_serving_protein, per_serving_carbs, per_serving_fats, tags, data) VALUES
('Classic Oatmeal Bowl', 'weight_loss', 'breakfast', 1, 350, 15, 50, 10, ARRAY['quick','budget-friendly'], '{"meal_name":"Classic Oatmeal Bowl","servings":1,"ingredients":[{"ingredient_name":"Rolled oats","grams":80,"calories":240,"protein_g":8,"carbs_g":42,"fats_g":4},{"ingredient_name":"Banana","grams":100,"calories":89,"protein_g":1,"carbs_g":23,"fats_g":0},{"ingredient_name":"Honey","grams":10,"calories":30,"protein_g":0,"carbs_g":8,"fats_g":0},{"ingredient_name":"Skim milk","grams":150,"calories":50,"protein_g":5,"carbs_g":7,"fats_g":0}]}'::jsonb),

('Protein Scrambled Eggs', 'muscle_gain', 'breakfast', 1, 450, 35, 15, 28, ARRAY['high-protein','quick'], '{"meal_name":"Protein Scrambled Eggs","servings":1,"ingredients":[{"ingredient_name":"Whole eggs","grams":150,"calories":210,"protein_g":18,"carbs_g":2,"fats_g":15},{"ingredient_name":"Egg whites","grams":100,"calories":52,"protein_g":11,"carbs_g":1,"fats_g":0},{"ingredient_name":"Whole wheat toast","grams":60,"calories":140,"protein_g":5,"carbs_g":24,"fats_g":2},{"ingredient_name":"Avocado","grams":30,"calories":48,"protein_g":1,"carbs_g":3,"fats_g":4}]}'::jsonb),

('Greek Yogurt Parfait', 'general_health', 'breakfast', 1, 380, 25, 45, 10, ARRAY['quick','no-cook'], '{"meal_name":"Greek Yogurt Parfait","servings":1,"ingredients":[{"ingredient_name":"Greek yogurt 0%","grams":200,"calories":120,"protein_g":20,"carbs_g":8,"fats_g":0},{"ingredient_name":"Granola","grams":40,"calories":160,"protein_g":4,"carbs_g":28,"fats_g":5},{"ingredient_name":"Mixed berries","grams":100,"calories":50,"protein_g":1,"carbs_g":12,"fats_g":0},{"ingredient_name":"Honey","grams":10,"calories":30,"protein_g":0,"carbs_g":8,"fats_g":0}]}'::jsonb),

('Overnight Oats', 'weight_loss', 'breakfast', 1, 320, 18, 42, 8, ARRAY['meal-prep','no-cook'], '{"meal_name":"Overnight Oats","servings":1,"ingredients":[{"ingredient_name":"Rolled oats","grams":60,"calories":180,"protein_g":6,"carbs_g":32,"fats_g":3},{"ingredient_name":"Greek yogurt 0%","grams":100,"calories":60,"protein_g":10,"carbs_g":4,"fats_g":0},{"ingredient_name":"Chia seeds","grams":10,"calories":49,"protein_g":2,"carbs_g":4,"fats_g":3},{"ingredient_name":"Blueberries","grams":80,"calories":46,"protein_g":1,"carbs_g":12,"fats_g":0}]}'::jsonb);

-- Lunch templates
INSERT INTO public.meal_templates (name, goal_type, meal_type, servings, per_serving_calories, per_serving_protein, per_serving_carbs, per_serving_fats, tags, data) VALUES
('Grilled Chicken Rice Bowl', 'muscle_gain', 'lunch', 1, 550, 45, 55, 12, ARRAY['high-protein','meal-prep'], '{"meal_name":"Grilled Chicken Rice Bowl","servings":1,"ingredients":[{"ingredient_name":"Chicken breast","grams":180,"calories":297,"protein_g":36,"carbs_g":0,"fats_g":6},{"ingredient_name":"Brown rice","grams":150,"calories":165,"protein_g":4,"carbs_g":35,"fats_g":1},{"ingredient_name":"Broccoli","grams":100,"calories":34,"protein_g":3,"carbs_g":7,"fats_g":0},{"ingredient_name":"Olive oil","grams":5,"calories":44,"protein_g":0,"carbs_g":0,"fats_g":5}]}'::jsonb),

('Tuna Salad Wrap', 'weight_loss', 'lunch', 1, 380, 32, 35, 12, ARRAY['quick','budget-friendly'], '{"meal_name":"Tuna Salad Wrap","servings":1,"ingredients":[{"ingredient_name":"Canned tuna in water","grams":130,"calories":130,"protein_g":28,"carbs_g":0,"fats_g":1},{"ingredient_name":"Whole wheat tortilla","grams":60,"calories":140,"protein_g":4,"carbs_g":24,"fats_g":3},{"ingredient_name":"Mixed greens","grams":50,"calories":10,"protein_g":1,"carbs_g":2,"fats_g":0},{"ingredient_name":"Light mayo","grams":15,"calories":50,"protein_g":0,"carbs_g":1,"fats_g":5},{"ingredient_name":"Cucumber","grams":50,"calories":8,"protein_g":0,"carbs_g":2,"fats_g":0}]}'::jsonb),

('Lentil Soup', 'general_health', 'lunch', 1, 420, 22, 58, 8, ARRAY['vegan','budget-friendly'], '{"meal_name":"Lentil Soup","servings":1,"ingredients":[{"ingredient_name":"Red lentils","grams":80,"calories":270,"protein_g":18,"carbs_g":46,"fats_g":1},{"ingredient_name":"Carrots","grams":60,"calories":25,"protein_g":1,"carbs_g":6,"fats_g":0},{"ingredient_name":"Onion","grams":50,"calories":20,"protein_g":1,"carbs_g":5,"fats_g":0},{"ingredient_name":"Olive oil","grams":10,"calories":88,"protein_g":0,"carbs_g":0,"fats_g":10},{"ingredient_name":"Spinach","grams":40,"calories":9,"protein_g":1,"carbs_g":1,"fats_g":0}]}'::jsonb);

-- Dinner templates
INSERT INTO public.meal_templates (name, goal_type, meal_type, servings, per_serving_calories, per_serving_protein, per_serving_carbs, per_serving_fats, tags, data) VALUES
('Salmon with Sweet Potato', 'muscle_gain', 'dinner', 1, 580, 42, 45, 20, ARRAY['high-protein','omega-3'], '{"meal_name":"Salmon with Sweet Potato","servings":1,"ingredients":[{"ingredient_name":"Salmon fillet","grams":180,"calories":330,"protein_g":36,"carbs_g":0,"fats_g":18},{"ingredient_name":"Sweet potato","grams":200,"calories":180,"protein_g":4,"carbs_g":42,"fats_g":0},{"ingredient_name":"Asparagus","grams":100,"calories":20,"protein_g":2,"carbs_g":4,"fats_g":0},{"ingredient_name":"Lemon juice","grams":15,"calories":4,"protein_g":0,"carbs_g":1,"fats_g":0}]}'::jsonb),

('Turkey Stir-Fry', 'weight_loss', 'dinner', 1, 420, 38, 30, 14, ARRAY['high-protein','quick'], '{"meal_name":"Turkey Stir-Fry","servings":1,"ingredients":[{"ingredient_name":"Ground turkey","grams":150,"calories":240,"protein_g":30,"carbs_g":0,"fats_g":12},{"ingredient_name":"Bell peppers","grams":100,"calories":30,"protein_g":1,"carbs_g":7,"fats_g":0},{"ingredient_name":"Zucchini","grams":100,"calories":17,"protein_g":1,"carbs_g":3,"fats_g":0},{"ingredient_name":"Brown rice","grams":80,"calories":88,"protein_g":2,"carbs_g":19,"fats_g":1},{"ingredient_name":"Soy sauce","grams":15,"calories":8,"protein_g":1,"carbs_g":1,"fats_g":0}]}'::jsonb),

('Pasta Bolognese', 'general_health', 'dinner', 1, 520, 30, 60, 16, ARRAY['comfort-food'], '{"meal_name":"Pasta Bolognese","servings":1,"ingredients":[{"ingredient_name":"Whole wheat pasta","grams":80,"calories":260,"protein_g":10,"carbs_g":52,"fats_g":2},{"ingredient_name":"Lean ground beef","grams":100,"calories":170,"protein_g":17,"carbs_g":0,"fats_g":10},{"ingredient_name":"Tomato sauce","grams":100,"calories":30,"protein_g":1,"carbs_g":6,"fats_g":0},{"ingredient_name":"Parmesan cheese","grams":15,"calories":60,"protein_g":4,"carbs_g":0,"fats_g":4}]}'::jsonb);

-- Snack templates
INSERT INTO public.meal_templates (name, goal_type, meal_type, servings, per_serving_calories, per_serving_protein, per_serving_carbs, per_serving_fats, tags, data) VALUES
('Protein Shake', 'muscle_gain', 'snack', 1, 250, 30, 20, 5, ARRAY['quick','post-workout'], '{"meal_name":"Protein Shake","servings":1,"ingredients":[{"ingredient_name":"Whey protein powder","grams":30,"calories":120,"protein_g":24,"carbs_g":3,"fats_g":1},{"ingredient_name":"Banana","grams":100,"calories":89,"protein_g":1,"carbs_g":23,"fats_g":0},{"ingredient_name":"Almond milk","grams":200,"calories":30,"protein_g":1,"carbs_g":1,"fats_g":1}]}'::jsonb),

('Apple with Peanut Butter', 'weight_loss', 'snack', 1, 200, 6, 25, 10, ARRAY['quick','no-cook'], '{"meal_name":"Apple with Peanut Butter","servings":1,"ingredients":[{"ingredient_name":"Apple","grams":150,"calories":78,"protein_g":0,"carbs_g":21,"fats_g":0},{"ingredient_name":"Natural peanut butter","grams":20,"calories":118,"protein_g":5,"carbs_g":4,"fats_g":10}]}'::jsonb),

('Trail Mix', 'general_health', 'snack', 1, 280, 8, 25, 18, ARRAY['no-cook','portable'], '{"meal_name":"Trail Mix","servings":1,"ingredients":[{"ingredient_name":"Almonds","grams":20,"calories":116,"protein_g":4,"carbs_g":4,"fats_g":10},{"ingredient_name":"Dried cranberries","grams":20,"calories":62,"protein_g":0,"carbs_g":17,"fats_g":0},{"ingredient_name":"Dark chocolate chips","grams":15,"calories":80,"protein_g":1,"carbs_g":9,"fats_g":5},{"ingredient_name":"Pumpkin seeds","grams":10,"calories":55,"protein_g":3,"carbs_g":1,"fats_g":5}]}'::jsonb);

-- ================================================
-- SEED WORKOUT TEMPLATES
-- ================================================

INSERT INTO public.workout_templates (name, goal_type, difficulty, duration_minutes, equipment_type, tags, data) VALUES
('Full Body Strength A', 'muscle_gain', 'beginner', 45, 'gym', ARRAY['full-body','compound'], '{"workout_name":"Full Body Strength A","exercises":[{"exercise_name":"Barbell Squat","sets":3,"reps":10,"rest_seconds":90,"muscle_group":"Legs","how_to":"Stand with feet shoulder-width, bar on upper back. Squat until thighs parallel to floor. Drive through heels to stand."},{"exercise_name":"Bench Press","sets":3,"reps":10,"rest_seconds":90,"muscle_group":"Chest","how_to":"Lie on bench, grip bar slightly wider than shoulders. Lower to chest, press up to lockout."},{"exercise_name":"Bent-Over Row","sets":3,"reps":10,"rest_seconds":90,"muscle_group":"Back","how_to":"Hinge at hips, pull barbell to lower chest. Squeeze shoulder blades at top."},{"exercise_name":"Overhead Press","sets":3,"reps":10,"rest_seconds":90,"muscle_group":"Shoulders","how_to":"Press barbell from shoulders to overhead. Keep core tight."},{"exercise_name":"Plank","sets":3,"reps":30,"rest_seconds":60,"muscle_group":"Core","how_to":"Hold a straight line from head to heels on forearms. Engage core throughout."}]}'::jsonb),

('Full Body Strength B', 'muscle_gain', 'beginner', 45, 'gym', ARRAY['full-body','compound'], '{"workout_name":"Full Body Strength B","exercises":[{"exercise_name":"Romanian Deadlift","sets":3,"reps":10,"rest_seconds":90,"muscle_group":"Hamstrings","how_to":"Hold barbell at hips. Hinge forward keeping back flat. Lower until stretch in hamstrings, then stand."},{"exercise_name":"Incline Dumbbell Press","sets":3,"reps":10,"rest_seconds":90,"muscle_group":"Upper Chest","how_to":"Set bench to 30 degrees. Press dumbbells from chest level to full extension."},{"exercise_name":"Lat Pulldown","sets":3,"reps":10,"rest_seconds":90,"muscle_group":"Back","how_to":"Pull bar to upper chest, squeeze lats. Control the return."},{"exercise_name":"Dumbbell Lateral Raise","sets":3,"reps":12,"rest_seconds":60,"muscle_group":"Shoulders","how_to":"Raise dumbbells to sides until arms parallel to floor. Lower slowly."},{"exercise_name":"Cable Crunch","sets":3,"reps":15,"rest_seconds":60,"muscle_group":"Core","how_to":"Kneel below cable. Crunch down bringing elbows toward knees."}]}'::jsonb),

('Upper Body Push', 'muscle_gain', 'intermediate', 50, 'gym', ARRAY['upper-body','push'], '{"workout_name":"Upper Body Push","exercises":[{"exercise_name":"Flat Bench Press","sets":4,"reps":8,"rest_seconds":90,"muscle_group":"Chest","how_to":"Lie flat on bench. Lower bar to mid-chest, press up explosively."},{"exercise_name":"Overhead Press","sets":4,"reps":8,"rest_seconds":90,"muscle_group":"Shoulders","how_to":"Press barbell from front shoulders to overhead lockout."},{"exercise_name":"Incline Dumbbell Fly","sets":3,"reps":12,"rest_seconds":60,"muscle_group":"Upper Chest","how_to":"On incline bench, lower dumbbells in wide arc, squeeze chest to bring together."},{"exercise_name":"Tricep Dips","sets":3,"reps":10,"rest_seconds":60,"muscle_group":"Triceps","how_to":"Lower body on parallel bars until upper arms parallel. Press up to lockout."},{"exercise_name":"Lateral Raises","sets":3,"reps":15,"rest_seconds":60,"muscle_group":"Shoulders","how_to":"Raise dumbbells to sides, slight bend in elbows. Pause at top."}]}'::jsonb),

('Upper Body Pull', 'muscle_gain', 'intermediate', 50, 'gym', ARRAY['upper-body','pull'], '{"workout_name":"Upper Body Pull","exercises":[{"exercise_name":"Pull-Ups","sets":4,"reps":8,"rest_seconds":90,"muscle_group":"Back","how_to":"Hang from bar, pull chin above bar. Lower with control."},{"exercise_name":"Barbell Row","sets":4,"reps":8,"rest_seconds":90,"muscle_group":"Back","how_to":"Hinge at hips, row bar to lower chest. Squeeze shoulder blades."},{"exercise_name":"Face Pulls","sets":3,"reps":15,"rest_seconds":60,"muscle_group":"Rear Delts","how_to":"Pull rope to face level, externally rotating shoulders. Squeeze rear delts."},{"exercise_name":"Barbell Curl","sets":3,"reps":12,"rest_seconds":60,"muscle_group":"Biceps","how_to":"Curl bar with strict form. Lower slowly."},{"exercise_name":"Hammer Curls","sets":3,"reps":12,"rest_seconds":60,"muscle_group":"Biceps","how_to":"Curl dumbbells with neutral grip. Keep elbows stationary."}]}'::jsonb),

('Lower Body Power', 'muscle_gain', 'intermediate', 55, 'gym', ARRAY['lower-body','compound'], '{"workout_name":"Lower Body Power","exercises":[{"exercise_name":"Back Squat","sets":4,"reps":8,"rest_seconds":120,"muscle_group":"Legs","how_to":"Bar on upper back. Squat to parallel or below. Drive through heels."},{"exercise_name":"Romanian Deadlift","sets":4,"reps":8,"rest_seconds":90,"muscle_group":"Hamstrings","how_to":"Hinge at hips with barbell. Feel stretch in hamstrings, stand tall."},{"exercise_name":"Bulgarian Split Squat","sets":3,"reps":10,"rest_seconds":60,"muscle_group":"Quads","how_to":"Rear foot elevated on bench. Lunge down until front thigh parallel."},{"exercise_name":"Leg Curl","sets":3,"reps":12,"rest_seconds":60,"muscle_group":"Hamstrings","how_to":"Curl weight toward glutes. Squeeze at top, lower slowly."},{"exercise_name":"Calf Raises","sets":4,"reps":15,"rest_seconds":60,"muscle_group":"Calves","how_to":"Rise onto toes, pause at top. Lower until stretch in calves."}]}'::jsonb),

('Home HIIT Circuit', 'weight_loss', 'beginner', 30, 'bodyweight', ARRAY['hiit','home','no-equipment'], '{"workout_name":"Home HIIT Circuit","exercises":[{"exercise_name":"Jumping Jacks","sets":3,"reps":20,"rest_seconds":30,"muscle_group":"Full Body","how_to":"Jump feet wide, arms overhead. Jump feet together, arms down. Repeat briskly."},{"exercise_name":"Bodyweight Squats","sets":3,"reps":15,"rest_seconds":30,"muscle_group":"Legs","how_to":"Stand shoulder-width, squat until thighs parallel. Stand up."},{"exercise_name":"Push-Ups","sets":3,"reps":10,"rest_seconds":30,"muscle_group":"Chest","how_to":"Hands shoulder-width, lower chest to floor, push up. Modify on knees if needed."},{"exercise_name":"Mountain Climbers","sets":3,"reps":20,"rest_seconds":30,"muscle_group":"Core","how_to":"In plank, alternate driving knees toward chest rapidly."},{"exercise_name":"Burpees","sets":3,"reps":8,"rest_seconds":45,"muscle_group":"Full Body","how_to":"Squat down, jump feet back to plank, push-up, jump feet forward, jump up."}]}'::jsonb),

('Fat Burn Cardio', 'weight_loss', 'beginner', 25, 'bodyweight', ARRAY['cardio','home'], '{"workout_name":"Fat Burn Cardio","exercises":[{"exercise_name":"High Knees","sets":3,"reps":30,"rest_seconds":30,"muscle_group":"Cardio","how_to":"Run in place, driving knees above hip level. Pump arms."},{"exercise_name":"Squat Jumps","sets":3,"reps":12,"rest_seconds":30,"muscle_group":"Legs","how_to":"Squat down, explode upward jumping. Land softly, repeat."},{"exercise_name":"Plank Jacks","sets":3,"reps":15,"rest_seconds":30,"muscle_group":"Core","how_to":"In plank position, jump feet wide then together. Keep hips stable."},{"exercise_name":"Lunges","sets":3,"reps":12,"rest_seconds":30,"muscle_group":"Legs","how_to":"Step forward, lower back knee toward floor. Push back to start. Alternate legs."},{"exercise_name":"Bicycle Crunches","sets":3,"reps":20,"rest_seconds":30,"muscle_group":"Core","how_to":"Lie on back, alternate bringing elbow to opposite knee in cycling motion."}]}'::jsonb),

('Functional Fitness', 'general_health', 'beginner', 35, 'minimal', ARRAY['functional','balanced'], '{"workout_name":"Functional Fitness","exercises":[{"exercise_name":"Goblet Squat","sets":3,"reps":12,"rest_seconds":60,"muscle_group":"Legs","how_to":"Hold dumbbell at chest. Squat deep with upright torso. Stand tall."},{"exercise_name":"Dumbbell Row","sets":3,"reps":10,"rest_seconds":60,"muscle_group":"Back","how_to":"One hand on bench, row dumbbell to hip. Squeeze back. Switch sides."},{"exercise_name":"Push-Ups","sets":3,"reps":10,"rest_seconds":60,"muscle_group":"Chest","how_to":"Lower chest to floor with straight body. Push up to full extension."},{"exercise_name":"Dead Bug","sets":3,"reps":10,"rest_seconds":45,"muscle_group":"Core","how_to":"Lie on back, arms up, knees at 90°. Lower opposite arm and leg. Alternate."},{"exercise_name":"Glute Bridge","sets":3,"reps":15,"rest_seconds":45,"muscle_group":"Glutes","how_to":"Lie on back, feet flat. Push hips up squeezing glutes. Lower slowly."}]}'::jsonb);
